//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosEnvios
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESOS
    {
        public int CODIGO { get; set; }
        public int CIUD_ORIG { get; set; }
        public int CIUD_DEST { get; set; }
        public int PRECIOKL { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual CIUDAD CIUDAD1 { get; set; }
    }
}
